services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: activitydb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: activitydb_test
    ports:
      - "5433:5432"
    volumes:
      - dbtestdata:/var/lib/postgresql/data

volumes:
  dbdata:
  dbtestdata:
